version: "3.7"

services:

  adminer:
    image: adminer
    restart: always
    ports:
      - 80:8080
    depends_on:
      db:
        condition: service_healthy
    links:
      - "db:db"
    profiles:
      - db-dev

  db:
    image: mariadb:latest
    volumes:
      - ./db/mysql/sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    healthcheck:
      test: pwd
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s
    profiles:
      - db-dev
      - dev
      - test
      - prod
      - nightly-batch

  db-neo4j:
    image: neo4j
    healthcheck:
      test: pwd
      interval: 10s
      retries: 5
      start_period: 20s
      timeout: 10s
    ports:
      - 7474:7474 # http
      - 7687:7687 # bolt
    environment:
      - NEO4J_AUTH=$NEO4J_AUTH
    profiles:
      - db-dev
      - dev
      - test
      - prod
      - nightly-batch

  py-neo4j-seed:
    build: db/neo4j
    healthcheck:
        test: "exit 0"
    command: sh -c "/wait && python app.py"
    environment:
      - NEO4J_AUTH=$NEO4J_AUTH
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
      - WAIT_HOSTS=db-neo4j:7687
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      db-neo4j:
        condition: service_healthy
        restart: true
    volumes:
      - ./db/neo4j/bin:/code
    profiles:
      - db-dev
      - dev
      - test
      - prod
      - nightly-batch
